Terraform 1
Otus-DevOps-2022-11/AvallaSD_infra pull request #5
Opened 2023-01-18 08:05 UTC by AvallaSD

# Выполнено ДЗ №8

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Настроено создание 3х ВМ, две с приложением, одна как балансировщик. 
 - При падении одной из двух вм, приложение так же доступно по внешнему адресу балансировщика

## Как проверить работоспособность:
 - 158.160.34.163

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-01-19 09:42 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий к файлу
Нужно внести небольшие правки
ДЗ возвращаю на доработку

2023-01-19 09:42 UTC, mrgreyves commented on terraform/main.tf
> +  required_version = ">= 0.35"
Ошибка в определении версии провайдера
1 - можно попробовать указать корректно
2 - можно удалить строку, после этого будет использоваться последняя версия провайдера

2023-01-19 11:37 UTC, AvallaSD commented on terraform/main.tf
> +  required_version = ">= 0.35"
Локально у меня все запустилось
Я брал образец с инструкции яндекса
https://cloud.yandex.ru/docs/tutorials/infrastructure-management/terraform-quickstart
![image](https://user-images.githubusercontent.com/60776606/213432667-15694b57-1771-4f82-a79c-b66d9772f04c.png)

Почему у них тогда так указано?

2023-01-19 11:47 UTC, AvallaSD commented on terraform/main.tf
> +  required_version = ">= 0.35"
Удаление строки не повлияло на успех прохождения тестов

2023-01-21 14:28 UTC, mrgreyves approved these changes
Здравствуйте!)
Тут история связана с тем, что в какой то момент поменялось определение провайдера для терраформа =)
ДЗ принимаю =)

2023-01-21 14:30 UTC, AvallaSD commented
Добрый день!

Почему тогда у меня сработало, а в тестах нет? В чем разница окружений?

On Sat, 21 Jan 2023 at 18:28, Vladimir Drozdetskiy ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Здравствуйте!)
> Тут история связана с тем, что в какой то момент поменялось определение
> провайдера для терраформа =)
> ДЗ принимаю =)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2022-11/AvallaSD_infra/pull/5#pullrequestreview-1264629759>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOPWBHSBRPHILRORN55G33LWTPXBXANCNFSM6AAAAAAT6YNI6A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-23 11:16 UTC, merged