Terraform 2
Otus-DevOps-2022-11/AvallaSD_infra pull request #6
Opened 2023-01-24 10:41 UTC by AvallaSD

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-01-28 14:31 UTC, mrgreyves requested changes
Здравствуйте!)
У вас не хватает достаточно большого количества файлов
Так же перед коммитом секцию с провайдером лучше закомментировать.

2023-02-05 10:00 UTC, AvallaSD commented
Файлы tfvars добавлены в папки prod и stage. Аналогичный файл удален из корневой директории terraform, т.к. там не осталось ни одного файла .tf. Файл vpc по инструкции надо было удалить и использовать переменные. Файл storage-bucket относится к заданию со * за которое я не брался. Остальные все файлы на месте. Секцию с провайдером закоммитил

2023-02-05 10:59 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий к файлу, нужно задать дефолтные параметры для переменных =)
Приключение на 20 минут =)

2023-02-05 10:59 UTC, mrgreyves commented on terraform/modules/app/main.tf
> +      image_id = var.app_disk_image
Для переменных стоит указать дефолтные значения =)

2023-02-05 11:12 UTC, AvallaSD commented on terraform/modules/app/main.tf
> +      image_id = var.app_disk_image
Готово

2023-02-05 11:12 UTC, AvallaSD commented
Правки внесены

2023-02-08 12:25 UTC, mrgreyves commented
Здравствуйте!
Не везде закоммитили провайдера

2023-02-10 13:23 UTC, AvallaSD commented
Исправил

On Wed, 8 Feb 2023 at 17:25, Vladimir Drozdetskiy ***@***.***>
wrote:

> Здравствуйте!
> Не везде закоммитили провайдера
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2022-11/AvallaSD_infra/pull/6#issuecomment-1422514404>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOPWBHSY6HJI6K5B3OCOCGTWWOGENANCNFSM6AAAAAAUE5KLAI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-11 15:49 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув =)

2023-02-11 15:49 UTC, mrgreyves commented on terraform/modules/app/main.tf
> +      image_id = var.app_disk_image
Закомментируйте провайдер и пушните =)
Посмотрим что скажет =)

2023-02-11 15:49 UTC, mrgreyves commented on terraform/stage/main.tf
> +terraform {
тут провайдер не нужен =)

2023-02-11 15:55 UTC, merged